name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: kawamataryo/lapras-card-readme@97beea07675cba3eded93eaeb71744413d7f8e8b # v1.3.0
        with:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          SHARE_ID: "tatsutakein"
          ICON_FIRST: "#212121"
          ICON_SECOND: "#818181"
          BACKGROUND_FIRST: "#232323"
          BACKGROUND_SECOND: "#6d6d6d"
          LANG: "en"
